### ISSUE TITLE
Interface for creating course dependencies

### ISSUE THREAD

**Issue by amarkrsinha1997** [navgurukul/kamaladevi#105]

**Comment by amarkrsinha1997** [comment]
![course-dependency](https://user-images.githubusercontent.com/33799812/57291011-3bce4280-70dc-11e9-8014-b268c6fc5792.jpg)

**Comment by amarkrsinha1997** [comment]
New page
/create-course-dependency

Access: Only Admin
Not Accessible without login

**Comment by amarkrsinha1997** [comment]
If the user is not an Admin the Page should be showing 
Sorry you don't have access to the page

**Comment by amarkrsinha1997** [comment]
- Single select of a course should call an API and would create a course-relation

**Comment by Rajat2008** [comment]
Hi @amarkrsinha1997 ,
Currently is there an API, that returns the list of all the courses?

**Comment by amarkrsinha1997** [comment]
> Hi @amarkrsinha1997 ,
> Currently is there an API, that returns the list of all the courses?
I think there is an API to get courseRelation not courses, I think we might need to create one
