### ISSUE TITLE
Markdown - Remove ngMeta properties

### ISSUE THREAD

**Issue by abhishekgupta92** [navgurukul/kamaladevi#14]
<img width="1349" alt="screen shot 2018-06-11 at 2 55 29 pm" src="https://user-images.githubusercontent.com/1681009/41223471-836e4f12-6d87-11e8-8f31-5f49fadba659.png">

the ngMeta properties

> name: Data Types
> completionMethod: manual

shouldn't be shown in the final UI.

**Comment by thePsguy** [comment]
I tried `content.replace(/```ngMeta.*```/g,'')`, works in online regex websites, but does not in the console / react app for some reason.

**Comment by credifiable** [comment]
It seems fixed now. Closing the issue.
