### ISSUE TITLE
Button to enrol in the course

### ISSUE THREAD

**Issue by abhishekgupta92** [navgurukul/kamaladevi#17]
There should be a button to enroll in the course if I haven't enrolled already. The button can come in the right bar as shown below:

<img width="1123" alt="screen shot 2018-06-11 at 3 11 00 pm" src="https://user-images.githubusercontent.com/1681009/41224250-ab298f9c-6d89-11e8-9d1f-813e69ef0c3d.png">

or as a complete bar just below the main toolbar. Something on following lines

![screenshot 2017-01-28 at 11 46 42](https://user-images.githubusercontent.com/1681009/41224449-25374932-6d8a-11e8-80cf-90cd819f2f38.png)

**Comment by credifiable** [comment]
@Praharsh92 - Please style the button which I have added.

**Comment by Praharsh92** [comment]
@credifiable button styled

**Comment by credifiable** [comment]
Closing
