### ISSUE TITLE
Automatic redirect from the login page

### ISSUE THREAD

**Issue by abhishekgupta92** [navgurukul/kamaladevi#18]
After logging in, even if I open the login page, I am not redirected to the home page. It should redirect me to the home page if I am logged in.

I am going to remove authentication from a lot of pages like - home page, course content pages (without enrolment), etc. so we will need to handle those cases once the APIs are ready for that.

**Comment by abhishekgupta92** [comment]
A new bug has been introduced because of this now. If I am not logged in, it keeps me redirecting to /home and back to /in an infinite loop.

**Comment by credifiable** [comment]
This has been fixed
