### ISSUE TITLE
URLS containing course content slug

### ISSUE THREAD

**Issue by abhishekgupta92** [navgurukul/kamaladevi#19]
URLs should contain course content slug when a particular course content is opened. 

E.g. existing Saral has following URL when you open a specific course content in any course:

http://saral.navgurukul.org/home/course/12/course-id/python/type/exercise/7-if-statement-flowcharts%2F7.4-if-flowchart-question3/slug?isEnrolled=true&isFacilitator=false&batchId=3

this can be simply
/course/python/exercise/7-if-statement-flowcharts%2F7.4-if-flowchart-question3

Also, opening this URL (let's say you get this URL after being shared by someone) should directly open the relevant course content.

**Comment by credifiable** [comment]
The URLs now contains the slug, and the links are sharable. If any more information is needed in the URLs, please open another issue.
