### ISSUE TITLE
New error :-) - On opening homepage

### ISSUE THREAD

**Issue by abhishekgupta92** [navgurukul/kamaladevi#22]
<img width="1006" alt="screen shot 2018-06-12 at 10 28 48 am" src="https://user-images.githubusercontent.com/1681009/41270948-6fa3b57c-6e2b-11e8-86dc-49255ded6062.png">

`Warning: validateDOMNesting(...): <div> cannot appear as a descendant of <p>.
    in div (created by LinearProgress)
    in div (created by LinearProgress)
    in LinearProgress (created by WithStyles(LinearProgress))
    in WithStyles(LinearProgress) (at course-list.js:139)
    in p (created by Typography)
    in Typography (created by WithStyles(Typography))
    in WithStyles(Typography) (at course-list.js:138)
    in div (created by CardContent)
    in CardContent (created by WithStyles(CardContent))
    in WithStyles(CardContent) (at course-list.js:131)
    in div (created by Paper)
    in Paper (created by WithStyles(Paper))
    in WithStyles(Paper) (created by Card)
    in Card (created by WithStyles(Card))
    in WithStyles(Card) (at course-list.js:130)
    in div (created by Grid)
    in Grid (created by WithStyles(Grid))
    in WithStyles(Grid) (created by GridWrapper)
    in GridWrapper (at course-list.js:129)
    in div (created by Grid)
    in Grid (created by WithStyles(Grid))
    in WithStyles(Grid) (created by GridWrapper)
    in GridWrapper (at course-list.js:119)
    in div (at course-list.js:118)
    in div (at course-list.js:117)
    in CourseList (created by WithStyles(CourseList))
    in WithStyles(CourseList) (at home.js:11)
    in div (at home.js:9)
    in Home (at with-root.js:36)
    in MuiThemeProvider (at with-root.js:30)
    in WithRoot (created by App)
    in Container (created by App)
    in App
    in AppContainer`

**Comment by Praharsh92** [comment]
#22 fix commit on enhancement-1
