### ISSUE TITLE
CSS Formatting - right sidebar

### ISSUE THREAD

**Issue by abhishekgupta92** [navgurukul/kamaladevi#44]
`<style type="text/css" data-jss="" data-meta="MuiList">
.jss519 {
  margin: 0;
  padding: 0;
  position: relative;
  list-style: none;
}
.jss520 {
  padding-top: 8px;
  padding-bottom: 8px;
}
.jss521 {
  padding-top: 4px;
  padding-bottom: 4px;
}
.jss522 {
  padding-top: 0;
}
</style>`

`  padding-top: 8px;
  padding-bottom: 8px;
`
not needed to move from
![capture](https://user-images.githubusercontent.com/1681009/46568186-5da4f280-c95e-11e8-9203-dd5d4bc3bdd5.PNG)

to
![capture2](https://user-images.githubusercontent.com/1681009/46568187-6269a680-c95e-11e8-9276-85325ba62bd3.PNG)

or maybe reduce it to 2 px.

**Comment by amarkrsinha1997** [comment]
Need a bit help here I didn't get this one @abhishekgupta92

**Comment by abhishekgupta92** [comment]
Call :)
