### ISSUE TITLE
A complete list of courses in the main page separated by three types

### ISSUE THREAD

**Issue by abhishekgupta92** [navgurukul/kamaladevi#5]
A complete list of courses in the main page separated by three types:

a. Aap inn courses ko facilitate kar rahe hai
b. Aapke courses
c. Aap yeh courses mein enroll kar skte hai

Currently, only the third category is coming

Corresponding SARAL Screenshot:
<img width="682" alt="screen shot 2018-06-05 at 7 41 03 pm" src="https://user-images.githubusercontent.com/1681009/40981259-25bf0dcc-68f8-11e8-82cf-3de197837432.png">

Corresponding new SARAL Screenshot:
<img width="1436" alt="screen shot 2018-06-05 at 7 42 29 pm" src="https://user-images.githubusercontent.com/1681009/40981340-5191a0b8-68f8-11e8-81eb-34da2191ae78.png">

**Comment by abhishekgupta92** [comment]
There is some problem with the grid:

<img width="1303" alt="screen shot 2018-06-11 at 5 08 48 pm" src="https://user-images.githubusercontent.com/1681009/41229592-36bf8876-6d9a-11e8-8ee6-576cbb9cad12.png">

Actual grid:
<img width="521" alt="screen shot 2018-06-11 at 5 09 45 pm" src="https://user-images.githubusercontent.com/1681009/41229615-45506c48-6d9a-11e8-86b4-cecaf867f415.png">


As per my understanding, the third category of courses "which you can facilitate" or "Aap inn courses ko facilitate kar rahe hai" isn't being shown properly as the third category.

Also, the sequence of the categories will be as following:

a. Aap inn courses ko facilitate kar rahe hai
b. Aapke courses
c. Aap yeh courses mein enroll kar skte hai

**Comment by credifiable** [comment]
Closing, as fixed in #6 .
