### ISSUE TITLE
Course card on Main Page

### ISSUE THREAD

**Issue by abhishekgupta92** [navgurukul/kamaladevi#6]
1. Use of material card for displaying the list of the courses
2. Add a description of the courses 
3. Add progress to the courses in terms of percentage through a progress bar for the "enrolled courses" - i.e. type 2 - Aapke Courses

Screenshot for existing angular view:

<img width="444" alt="screen shot 2018-06-05 at 7 44 36 pm" src="https://user-images.githubusercontent.com/1681009/40981465-9d254304-68f8-11e8-8b2d-6fb9ad7a5ada.png">

**Comment by thePsguy** [comment]
Since below is all the info about the course there is,
<img width="370" alt="image" src="https://user-images.githubusercontent.com/10270894/41158954-7220ebfc-6b48-11e8-9e3e-74a29cd53575.png">

The value of the progress bar would be `daysSinceEnrolled/daysToComplete`, right?

**Comment by abhishekgupta92** [comment]
completedSubmissions/totalExercises

**Comment by thePsguy** [comment]
#### I think this issue can now be closed:
<img width="450" alt="image" src="https://user-images.githubusercontent.com/10270894/41180963-b1514840-6b8d-11e8-935a-caea16163f60.png">

**Comment by abhishekgupta92** [comment]
Looks great. There is just a minor UI issue. Check the screenshot for reference.

<img width="1270" alt="screen shot 2018-06-11 at 2 59 13 pm" src="https://user-images.githubusercontent.com/1681009/41223649-063defc4-6d88-11e8-9e49-abd056e0f939.png">

There are two minor issues:

1. The distance between the cards in the upper grid.
2. Headings are aligned left and center, instead of all being center aligned.
3. All descriptions are same. 

Enhancement:
I think we can forgo "Preview Button" and make the entire card clickable. To enroll in a course the button should come anyhow inside the course. Creating a different issue for that.

**Comment by thePsguy** [comment]
Sure!
@abhishekgupta92 Regarding 3 though:
The description would have to be updated on the server itself. Presently all courses have the same Java description as can be seen in above screenshot.

This can be seen in the existing platform as well: http://saral.navgurukul.org/home

The description received from the server is the same for all courses.

**Comment by abhishekgupta92** [comment]
Thanks, will get it fixed :-)

--
P.S. Global warming is not cool! Save paper, save earth :)

**Comment by Praharsh92** [comment]
1 & 2 and other styling fix on course-list.js committed as "#6 course-list styles" on branch- enhancements1. As i dont have the object structure for facilitatingCourses, havnt styled that part of the page.

**Comment by credifiable** [comment]
Don't know how to add facilitating courses. Closing in favour of fix by @Praharsh92
