### ISSUE TITLE
Course Content Switcher

### ISSUE THREAD

**Issue by abhishekgupta92** [navgurukul/kamaladevi#7]
<img width="340" alt="screen shot 2018-06-08 at 12 00 27 am" src="https://user-images.githubusercontent.com/1681009/41118805-aeb4bfa2-6aae-11e8-9511-0f0d1e55040c.png">

Features of this course content switcher
1. Display all the content headings in a hierarchical manner

2. On clicking on any content heading
  - if content link - update the left-hand side content view
  - if category link (i.e. has children) - close every category and open this one (like an accordion view)

3. For all the content headings according to the server status, the circular image should be replaced with the status like - submitted, accepted, rejected. Use any images and ask @abhishekgupta92 to replace with the proper images if you don't want to spend time on searching for images.

**Comment by credifiable** [comment]
Fixed by @Praharsh92
