### ISSUE TITLE
Courses Dependency System.

### ISSUE THREAD

**Issue by amarkrsinha1997** [navgurukul/kamaladevi#72]
There should be a courses dependency system so that a student knows the track of there studying and can follow it sequence wise and doesn't get distracted with so many courses around.

The courses dependency system will work such as only those courses would be shown to the students for which all the dependency courses have been completed or there are no such dependency courses.

Once the student has completed all the dependency courses for any course, the course should be unlocked and available to get enroll for the student.

**GET /courses** route will contain extra array object dependencyCourses which will have an extra field dependencyCourses which will contain an array of a name of the courses on which the course depends.

### What needs to be done:
The Admins can see all the courses with the there dependency courses name below it
but student won't be able to see the courses have dependencyCourses left to be completed
as so they don't get distracted with so many contents and so they can't enroll it also.

**Comment by abhishekgupta92** [comment]
but student won't be able to see the courses has dependencyCourses left to be completed
as so they don't get distracted with so many contents and so they can't enroll it also.



Students will be able to see all such courses under a new heading which would say - 

## Yeh courses aap future mei kar sakte hai:

These courses will also be available on the main page.

**Comment by ajitAcc** [comment]
Hi @amarkrsinha1997 send mail regarding what need to be display, please check with Abhishek on the same 
For example Total available courses 
A B C  (B & C are depends on completion on A)

D E F G (E F & G are depends on completion on D)

H I G K L (I G K L depends on completion of H)

M  (alone course M)

N 

O P Q R S T

===============Home  Screen 1 (when login user have not enrolled in any course)
Aap yeh courses mein enroll kar skte hai

A D H M N O   (all prelims course will be displayed) 


================================Screen 2 (When user enrolled to Courses A and H)

Courses jis mein aap enrolled hai
A H

Yeh courses aap future mei kar sakte hai:
nothing now (as both A & H are not 70% completed)


Aap yeh courses mein enroll kar skte hai
D M N O   (all prelims course minus enrolled courses will be displayed)

===========================Screen 3 (When user completed course A 70%)
Courses jis mein aap enrolled hai
A H  - (A is compleetd 70% H is only 50%)

Yeh courses aap future mei kar sakte hai:
B C - Display only for A as A is 70% completed


Aap yeh courses mein enroll kar skte hai
D M N O

**Comment by amarkrsinha1997** [comment]
reviewed

**Comment by Rajat2008** [comment]
Hi @amarkrsinha1997 ,
As per the our initial discussion, no changes are required in this issue, as we are already creating an interface to add mentors.
