### ISSUE TITLE
Previous and Next Buttons in Course Content View

### ISSUE THREAD

**Issue by abhishekgupta92** [navgurukul/kamaladevi#8]
There should be previous and next buttons in the course content view, clicking on which, the user should be able to navigate to the other or previous part of the courses. Doing so will also update the right-hand side content switcher.

<img width="618" alt="screen shot 2018-06-08 at 12 05 50 am" src="https://user-images.githubusercontent.com/1681009/41119093-8288597e-6aaf-11e8-879a-2cb17a8a7117.png">

**Comment by credifiable** [comment]
@Praharsh92 - Can you please put up the buttons, I will bind the functionalities

**Comment by Praharsh92** [comment]
@credifiable buttons in place

**Comment by credifiable** [comment]
Previous and next buttons are functional now.
