### ISSUE TITLE
No Peer Review Requests

### ISSUE THREAD

**Issue by abhishekgupta92** [navgurukul/kamaladevi#83]
http://saral.navgurukul.org/assignment-review
- There is a empty screen message.  (no peer review requests message)

## Part I
- Change the screen to as attached. (CSS/HTML)

## Part II

- The screen should only have a loader, only when there are no requests that message should be shown, and if the requests are there show the requests. (React)

**Comment by amarkrsinha1997** [comment]
@Ranipandit this is done right?

**Comment by Ranipandit** [comment]
Yes, it is done.
