### ISSUE TITLE
Should work without authentication

### ISSUE THREAD

**Issue by abhishekgupta92** [navgurukul/kamaladevi#88]
- Only for functionalities where login is indispensable, the login popup should be shown.
- Landing Page - should be course view directly

**Comment by ajitAcc** [comment]
@abhishekgupta92 please provide wireframe for more details

**Comment by Rajat2008** [comment]
hi @amarkrsinha1997 ,

Could you please list down the scenarios where the login is indispensable and the pop needs to be shown.

**Comment by ajitAcc** [comment]
@amarkrsinha1997 , Need to have search control/button on home page where all coursers were displayed. So that user can search for specific course available from store and based on this all courses will get displayed

**Comment by amarkrsinha1997** [comment]
## API which doesn't require authentication.
/courses
/courses/{courseId}/exercises
/courses/{coursesId/exercise/getBySlug 
## Make some HOC for authentication so it can be used in any other component if required

**Comment by ajitAcc** [comment]
Hi @amarkrsinha1997 as discussed in call
1. When guest user click on particular enroll course, a login popup window appear for user to login to site.
2. If login success then user must redirect to same page where he is trying to enroll that particular course.   
3. If login fail then error message will appear on same login popup window without any redirect to course page.

**Comment by Rajat2008** [comment]
@amarkrsinha1997 , 
As discussed, the user should be directly redirected to '/home' when the user clicks on saral.navagurukul,org. index.js should not be loaded.

**Comment by ajitAcc** [comment]
Hi @amarkrsinha1997 as per review finding on 3/28 following need to be done.
1. Guest user must see all question but no need to show exercise submission. 
2. User should be directly redirected to '/home' when the user clicks on saral.navagurukul,org. index.js should not be loaded.
3. For manual peer review request , user should redirect to login page.
4. Need to handle for non login case in API getExerciseSubmissionAPI

**Comment by amarkrsinha1997** [comment]
reviewed and tested
