### ISSUE TITLE
Mentors should be able to mark a course or an assignment completed even without a submission for their mentee

### ISSUE THREAD

**Issue by abhishekgupta92** [navgurukul/kamaladevi#92]

**Comment by ajitAcc** [comment]
@abhishekgupta92 Need wireframe for how to design UI.

**Comment by amarkrsinha1997** [comment]
[Notes.pdf](https://github.com/navgurukul/kamaladevi/files/3027923/Notes.pdf)
- Material UI update
- The mentor-tree branch has incomplete work of the pdf
- The popup should be displayed on clicking the table cell to mark them completed both on exercises and courses.

**Comment by Rajat2008** [comment]
Hi @amarkrsinha1997 , for the course Progress report how will the application behave if -
1, A student is not enrolled in a course.
2,A course does not have any exercises.

**Comment by amarkrsinha1997** [comment]
No exercises available for the courses

> Hi @amarkrsinha1997 , for the course Progress report how will the application behave if -
> 1, A student is not enrolled in a course.
> 2,A course does not have any exercises.

**Comment by amarkrsinha1997** [comment]
- Only the courses in which my mentees are enrolled should be shown
- No link to exercises report for the courses which doesn't have any exercises or we can show no exercises  available for the courses

**Comment by amarkrsinha1997** [comment]
No exercises for courses:
Show green bar completed and on hover show No Exercises.

**Comment by Rajat2008** [comment]
The popup should be displayed on clicking the table cell to mark them completed both on exercises and courses.

Hi @amarkrsinha1997 ,
In the above requirement, what is the behavior when the user clicks on any cell for which the status of the exercise is 'pending approval'.

**Comment by Rajat2008** [comment]
For the course completion, A small pop up should open on clicking on any of the cells of the 'Course Progress' report. This pop up will give the mentor  the ability to mark a course as 'Complete' manually.

For individual exercises in the course, A pop-up should open on click, the contents of the pop up will be 
similar to right side panel of the 'peer review' screen. This pop-up will allow the mentor to mark an exercise as 'Complete'.

@amarkrsinha1997

**Comment by amarkrsinha1997** [comment]
Done
