### ISSUE TITLE
Integrate Sentry

### ISSUE THREAD

**Issue by abhishekgupta92** [navgurukul/kamaladevi#93]

**Comment by ajitAcc** [comment]
What needs to be logged:
•	API name.
•	User Id.
•	Date.
for the code base error.
•	Line number.
•	File.
for the user interaction error.
•	log the payloads.
log the response errors that are rejected.

**Comment by ajitAcc** [comment]
@amarkrsinha1997
Awaiting input from Amar for which specific place in GUI this logs need to implement.

**Comment by ajitAcc** [comment]
Awaiting input from Amar for which specific place in GUI these logs need to implement

**Comment by amarkrsinha1997** [comment]
reviewed and tested working

**Comment by Rajat2008** [comment]
Sentry has been integrated in the React code .
To integrate sentry '@sentry/browser' has been used.
Sentry has been initialized in the componentDidMount hook of the pages and the errors have been catched in the componentDidCatch lifecycle hook.
