### ISSUE TITLE
Integrate GA

### ISSUE THREAD

**Issue by abhishekgupta92** [navgurukul/kamaladevi#94]

**Comment by amarkrsinha1997** [comment]
Need to test on production and cleared from here

**Comment by ajitAcc** [comment]
Will need to test on live production server. So no need to do anything right now for this issue.

**Comment by Rajat2008** [comment]
GA has been integated with the Kamaladevi.
the 'react-ga' library has been used for this.

the GA tag has been inserted in the course-list component.

**Comment by amarkrsinha1997** [comment]
@Rajat2008 we have to record all the pages in Kamala Devi

**Comment by amarkrsinha1997** [comment]
Done
