### ISSUE TITLE
Filter feature to search courses

### ISSUE THREAD

**Issue by amarkrsinha1997** [navgurukul/kamaladevi#98]
@amarkrsinha1997 , Need to have search control/button on home page where all coursers were displayed. So that user can search for specific course available from store and based on this all courses will get displayed

_Originally posted by @ajitAcc in https://github.com/navgurukul/kamaladevi/issues/88#issuecomment-470450642_

**Comment by ajitAcc** [comment]
Hi @amarkrsinha1997 following need to implement for search feature.
1. Need one Edit box to enter course name, Go button.
2. Implement click event of Go button to call backend API( New API to create as in #3)to search for all available course in database.
3. Implement New API to get all course based on keyword entered with from davinci.courses where name like '%keyword%'.
Argument for New API - keyword enter by user.
Return object - Array of all available courses in davinci.courses table where name like '%keyword%'.
Json object
{
      "id": 12,
      "name": "Introduction to Javascript",
      "type": "js",
      "logo": "https://bit.ly/2S2Y1un",
      "shortDescription": "Hindi Tutorials to learn to write code in javascript",
      "sequenceNum": 10
    },
4. Display all returned course from course object returned from New API.

**Comment by ajitAcc** [comment]
Hi @amarkrsinha1997 following need to implement for search feature.
1.	Need one Edit box to enter course name, Go button.
2.	Implement click event of Go button to call backend API( New API to create as in #3)to search for all available course in database.
3.	Implement New API to get all course based on keyword entered with from davinci.courses where name like '%keyword%'.
Argument for New API - keyword enter by user.
Return object - Array of all available courses in davinci.courses table where name like '%keyword%'.
Json object
{
"id": 12,
"name": "Introduction to Javascript",
"type": "js",
"logo": "https://bit.ly/2S2Y1un",
"shortDescription": "Hindi Tutorials to learn to write code in javascript",
"sequenceNum": 10
},
Display all returned course from course object to home page.

**Comment by ajitAcc** [comment]
Hi @amarkrsinha1997 , as per discussion 
1. Search will be as given in this link for reference.
    https://ahfarmer.github.io/emoji-search/
2. Search will be done from all courses which were displayed on home page.
3. No API call for this features as search will be done only from available display courses. hence closing issue https://github.com/navgurukul/galileo/issues/108

**Comment by amarkrsinha1997** [comment]
reviewed and tested
